# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

stages:
    - name: base
    - name: live
      if: branch = master OR type = pull_request

jobs:
    include:
        - stage: base
          os: linux
          r: release
        - stage: live
          os: linux
          r: oldrel
        - os: linux
          r: 3.3
        - os: osx
          r: release
        - os: osx
          r: oldrel

sudo: false
cache: packages
after_success:
    - Rscript -e 'covr::codecov()'
