# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

stages:
    - name: base
      os: linux
      r: release
    - name: live
      if: branch = master OR type = pull_request
      os:
        - linux
        - osx
      r:
        - oldrel
        - release
        - 3.3

sudo: false
cache: packages
after_success:
    - Rscript -e 'covr::codecov()'
